### ISSUE TITLE
Add a LICENSE and a README.md

### ISSUE THREAD

**Issue by scorphus** [d42/fish-pip-completion#1]
Hello, thanks for this completion! :+1: 

Could you please add a LICENSE to the project? You see, I am already using it without knowing if I'm infringing any copyrights :smile: Also, a README.md would be great.

I'm eager to contribute, if you'd like I can open a pull-request with both these files. Just tell me what the license should be (MIT, BSD, GPLv?) and the copyright holder and year. I can suggest a README.md

Thanks!

**Comment by d42** [comment]
Cool, I didn't expect anyone to use it, besides me :3 I've added aforementioned stuff and regenerated the completions

**Comment by scorphus** [comment]
> Cool, I didn't expect anyone to use it, besides me :3 […]

Yeah! I use it a lot!

> I've added aforementioned stuff […]

Great, thanks!

> and regenerated the completions

I'm curious, though, as to how you generate them. Can you please teach me?

**Comment by d42** [comment]
first time i've used lots of regular expressions in vim but now it was this beautiful work of art
https://gist.github.com/d42/60e949cba5b6fe5a2a19
https://gist.github.com/d42/d698806847b3a83174d5
